[project]
name = "dats0001"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "corner>=2.3.0",
    "emcee>=3.1.6",
    "h5py>=3.16.0",
    "jax>=0.11.1",
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.2",
    "numdifftools>=0.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
    "tqdm>=4.70.1",
]

[tool.uv]
python-preference = "only-managed"
